### ISSUE TITLE
Why not as Library?

### ISSUE THREAD

**Issue by jlelse** [andrebts/login-basics#1]
If I want to use the code I have to copy all files.
Isn't it easier to create a library and publish it on jcenter?

**Comment by andrebts** [comment]
Hello JI Else,
the project is under the Sample category at
https://plus.google.com/communities/100609058582053363304/stream/82d5b5b4-e9df-4026-aff0-c79ee6241a25.
I didn't create a library because I'm very busy at the moment, however I
could notice that there's a lack of material, libraries and examples on the
matter of Login with Social Network. So making use of my available time,
that was the best I could do. But feel free to fork and change it as you
will.

**Comment by jlelse** [comment]
Ok thx.
I'll look if I find time to create a library for that...
